<!DOCTYPE html>
<html>
<head>
    <?php if (is_array($head_sections)) foreach ($head_sections as $section) e($section . "\n"); ?>
    <title><?php e($this->title); ?></title>
    <?php if (is_array($href_styles)) foreach ($href_styles as $style) e('<link type="text/css" href="%s?ver=%s" rel="stylesheet" />' . "\r\n", str_replace('//', '/', $style), APP_VER); ?>
    <?php if ($text_styles) e($text_styles); ?>
</head>
<body>
<?php e($the_body); ?>
<?php if (is_array($href_scripts)) foreach ($href_scripts as $script) e('<script type="text/javascript" src="%s?ver=%s"></script>' . "\r\n", str_replace('//', '/', $script), APP_VER); ?>
<?php if ($text_scripts) e($text_scripts); ?>
</body>
</html>
